export const allWords = [
    "eu", "tu", "ele", "ela", "nós", "vós", "eles", "elas", "me", "mim",
    "comigo", "te", "ti", "contigo", "se", "si", "consigo", "o", "a", "os", "as",
    "lhe", "lhes", "nos", "vos", "meu", "teu", "seu", "nosso", "vosso", "dele",
    "dela", "deles", "delas", "quem", "que", "qual", "quais", "quanto", "quantos",
    "quanta", "quantas", "este", "esta", "estes", "estas", "esse", "essa", "esses",
    "essas", "aquele", "aquela", "aqueles", "aquelas", "isto", "isso", "aquilo",
    "todo", "toda", "todos", "todas", "outro", "outra", "outros", "outras", "mesmo",
    "mesma", "mesmos", "mesmas", "algum", "alguma", "alguns", "algumas", "nenhum",
    "nenhuma", "nenhuns", "nenhumas", "muito", "muita", "muitos", "muitas", "pouco",
    "pouca", "poucos", "poucas", "tanto", "tanta", "tantos", "tantas", "qualquer",
    "quaisquer", "um", "uma", "uns", "umas", "até", "com", "contra", "de", "desde",
    "em", "entre", "para", "por", "sem", "sob", "sobre", "como", "ao", "e", "mas",
    "porém", "todavia", "contudo", "entretanto", "ou", "ora", "quer", "nem", "porque",
    "pois", "porquanto", "assim", "logo", "portanto", "enquanto", "é", "foi", "do",
    "da", "no", "na", "num", "numa", "O", "Embora", "mais", "Na", "dos", "A", "não",
    "Naquela", "foram", "deste", "Um", "já", "Para", "Os", "Uma", "pelo", "Ainda",
    "quando", "das", "Em", "pela", "Mas", "também", "desses", "No", "Mais", "Muitas",
    "Até", "Já", "Com", "ainda", "onde", "Do", "então", "Neste", "As", "Ao", "pelos",
    "De", "à", "É", "disso", "pelas", "Pela", "vez", "estão", "Este", "Aos", "às",
    "Como", "desse", "Enquanto", "Todas", "nas", "caso", "Pra", "dessa", "aos",
    "entanto", "Nos", "E", "Eu", "Assim", "através", "Isto", "Dessa", "Entre", "Que",
    "Isso", "Ela", "Alguns", "menos", "está", "pro", "abaixo", "Acerca", "dessas",
    "Esses", "Então", "Não", "neste", "Eles", "Se", "Quando", "tal", "Logo", "Por",
    "nele", "Pelo", "nesta", "Portanto", "Ou", "Algumas", "Foi", "Esta", "Também",
    "Sob", "Nenhum", "nessas", "Essa", "Essas", "naquele", "Contra", "Desde", "Ele",
    "Ma", "À", "Nas", "embora", "atrás", "Muitos", "nesse", "naquela", "Nesse",
    "desta", "Dos", "Desse"
  ];
